name: Reusable - Muzzle

on:
  workflow_call:
    inputs:
      cache-read-only:
        type: boolean
        required: false

permissions:
  contents: read

jobs:
  muzzle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ":instrumentation:muzzle1"
          - ":instrumentation:muzzle2"
          - ":instrumentation:muzzle3"
          - ":instrumentation:muzzle4"
      fail-fast: false
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4.2.2
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4.0.1
        with:
          cache-read-only: ${{ inputs.cache-read-only }}

      - name: Run muzzle
        run: ./gradlew ${{ matrix.task }}
